const screenNames = {
  HomeScreen: "HomeScreen",
  LoginScreen: "LoginScreen",
  SignUpScreen: "SignUpScreen",
  OnboardingScreen: "OnboardingScreen", 
  MainTabs: "MainTabs",

  MoreScreen: "MoreScreen",
  ChatsScreen: "ChatsScreen",
  MatchesScreen: "MatchesScreen",
  RecentUserScreen: "RecentUserScreen",
  SearchScreen: "SearchScreen",
  DetailsScreen: "DetailsScreen",
  NewsScreen: "NewsScreen",
  NewsDetailsScreen: "NewsDetailsScreen",
  ServicesScreen: "ServicesScreen",
  ShortlistedScreen: "ShortlistedScreen",
  UpdateProfileScreen: "UpdateProfileScreen",
  ServieProviderScreen: "ServiceProviderScreen",
  ServieProviderScreen: "ServiceProviderScreen",
  SubscriptionScreen: "SubscriptionScreen",
  ServieProviderDetailsScreen: "ServiceProviderDetailsScreen",
  NotificationScreen: "NotificationScreen",
  ChatsDetailsScreen: "ChatsDetailsScreen",
  AboutusScreen: "AboutusScreen",
  ContactScreen: "ContactScreen",
  ShortlistedScreen: "ShortlistedScreen",
  ForgotPassword: "ForgotPassword",
  ResetPassword: "ResetPassword",
  videoCallScreen: "videoCallScreen",
  PaymentHistoryScreen: "PaymentHistoryScreen",

};

export default screenNames;
