export const device_token = "kdfgdjfgsf5873456873jhbsjdf";

export const commonUtils = {
  nextText: "Next",
  getStarted: "Get Started",
  userCreatedSuccess: "Registration successful! Please login",
  EditProfile: "Edit Profile",
  loginSuccess: "Login successful",
  invalidCredentials: "Invalid credentials",
  unexpectedError: "An unexpected error occured",
  pleaseFillAllFields: "Please fill all fields",
  emailRequired: "Email is required",
  validEmail: "Please enter a valid email",
  passwordRequired: "Password is required",
  phoneRequired: "Phone number is required",
  confirmPasswordRequired: "Confirm password is required",
  nameRequired: "Name is required",
  validPassword: "Password must be between 6 to 10 characters long",
  validPhoneNumber: "Please enter a valid phone number",
  confirmValidPassword:
    "Confirm password must be between 6 to 10 characters long",
  viewAllText: "View All",
  noDataFound: "No data found",
  RecentlyJoined: "Recently Joined",
  NewMatches: "New Matches",
  recentNewsHeading: "Recent News",
  errorFetchingData: "Error in fetching data:",
  notAvailable: "Not available",
  logoutText: "Logout",
  areYouSureWantToLogout: "Are you sure you want to logout ?",
  moreTextHeading: "More",
  updateProfileHeading: "Update Profile",
  userLogoutSuccess: "User Logout Successfully",
  userLogoutError: "User Logout Failed",
  ShortlistedStext: "Shortlisted",
  casteRequire: "Caste is required",
  DateofBirthRequired: "Date of birth is required",
  birthTimeRequired: "Birth time is required",
  birthPlaceRequired: "Birth place is required",
  bloodGroupRequired: "Blood group is required",
  fatherNamerequired: "Father name is required",
  fatherOccupationrequired: "Father occupation is required",
  motherNamerequired: "Mother name is required",
  motherOccupationrequired: "Mother occupation is required",
  familyCityRequired: "Family city is required",
  familyaddressRequired: "Family address is required",
  gotrananiHalRequired: "Gotra nanihal is required",
  familyIncomeRquired: "Family income is required",
  familyTypeRquired: "Family type is required",
  familyStatusRquired: "Family status is required",
  serviesOfferd: "Services Offered",
  contactDetails: "Contact Details",
  continuePurchase: "Continue to Purchase",
  subscriptionheading: "Subscription",
  bestValue: "Best Value",
  mostPopular: "Most Popular",
  payMonthly: "Pay monthly",
  payYearly: "Pay yearly",
  NewsText: "News",
  ServiceProvider: "Service Providers",
  notifictionsText: "Notifications",
  chatsText: "Chats",
  lastSeenToday: "Online",
  aboutUsText: "About Us",
  refundText: "Refund Policy",
  privacyPolicyText: "Privacy Policy",
  termsAndConditionsText: "Terms and Conditions",
  contactUstext: "Contact Us",
  userUpateSuccess: "User updated successfully",

  shortlistedBYme: "Shortlisted by me",
  totalNews: "Total News",
  totalServices: "Total Services",
  PaymentHistory:"Payment History"
};
