const ImagePicker = {
  loginScreenLogo: require("../../assets/Images/login-screen-logo.png"),
  aboutusScreenLogo: require("../../assets/Images/login-bg.jpg"),
  splashScreenImage: require("../../assets/Images/splash.png"),
  intro1: require("../../assets/Images/intro1.png"),
  intro2: require("../../assets/Images/intro2.png"),
  intro3: require("../../assets/Images/intro3.png"),
  dummyUserImage: require("../../assets/Images/user-image-new.jpeg"),
  dummyUserImage2: require("../../assets/Images/dummyUser2.png"),
  placeholderIMage: require("../../assets/Images/default_error.png"),
  logoImage: require("../../assets/Images/matrimonix-logo.png"),
  dummyUserMale: require("../../assets/Images/dummy_m.png"),
  dummyUserGirl: require("../../assets/Images/dummy_f.png"),
  matchedIcon: require("../../assets/Images/matched-icon.png"),
  shortlistIcon: require("../../assets/Images/shortlisted-icon.png"),
  profileVisitorsIcon: require("../../assets/Images/profile-visit-icon.png"),
  interestIcon: require("../../assets/Images/love-interest.png"),
  newsIcon: require("../../assets/Images/news-text-icon.png"),
  videoCallImage: require("../../assets/Images/video-call.png"),
  dummyNoImage: require("../../assets/Images/dumyy-noimg.png"),
  aboutMySelf: require("../../assets/Images/about-myself.png"),
  importantDetailsIcons: require("../../assets/Images/imp-details-icon.png"),
  updateProfileBgBackImage: require("../../assets/Images/update-profile-banner-back.png"),
  updateProfileBgFrontImage: require("../../assets/Images/update-profile-banner-front.png"),
  familyIcon: require("../../assets/Images/family-icon.png"),
  lifestyleIcon: require("../../assets/Images/lifestyle-icon.png"),
  overviewIcon: require("../../assets/Images/overview-icon.png"),
  eyeICon: require("../../assets/Images/eyebro-eye-icon.png"),
  astroIcon: require("../../assets/Images/astro-icon.png"),
  locationIconImage: require("../../assets/Images/locate-cate-icon.png"),
  servicesOfferIcon: require("../../assets/Images/services-offer-icon.png"),
  pricingInfoIcon: require("../../assets/Images/pricing-info-icon.png"),
  galleryIconImage: require("../../assets/Images/gallery-cat-icon.png"),
  aboutUsImage: require("../../assets/Images/aboutUsImage.jpeg"),
  cameraIconImage: require("../../assets/Images/cam_enable.png"),
  cardCameraImage: require("../../assets/Images/card_camera.png"),
  cancelOptionImage: require("../../assets/Images/cards_cancel.png"),
  galleryOptionImage: require("../../assets/Images/gallery_card.png"),
  subscriptionHistoryImage: require("../../assets/Images/subcription-icon-image.png"),
  Add_More_Image: require("../../assets/Images/add_more.png"),
};

export default ImagePicker;
